# Generated by Django 4.1.3 on 2023-01-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='email',
            field=models.EmailField(default=11, max_length=254),
            preserve_default=False,
        ),
    ]
